Removed 30 Scapegoat Errors related to ComparingFloatingPointTypes
LBNL-UCB-STI/beam pull request #2994
Opened 2020-09-18 16:24 UTC by carloscaldas

Closes https://github.com/LBNL-UCB-STI/beam/issues/2990

2020-09-18 16:39 UTC, rajnikantsh commented on src/main/scala/beam/agentsim/agents/ridehail/TNCIterationStats.scala
> +    if (circleRadiusInMeters.equals(updatedRadius)) {
condition is reverse

2020-09-18 16:45 UTC, rajnikantsh requested changes
Except 1 condition all LGTM

2020-09-19 10:42 UTC, carloscaldas commented on src/main/scala/beam/agentsim/agents/ridehail/TNCIterationStats.scala
> +    if (circleRadiusInMeters.equals(updatedRadius)) {
fixed

2020-09-19 10:44 UTC, carloscaldas commented
Test now!

2020-09-19 10:44 UTC, carloscaldas commented
Test!

2020-09-19 10:52 UTC, aaltergot commented on src/main/scala/beam/agentsim/agents/choice/mode/RideHailDefaults.scala
> +  private val zero: Double = 0D
nit: I would suggest `0.0` format for Double literals (https://www.scala-lang.org/files/archive/spec/2.13/01-lexical-syntax.html).
Also DEFAULT_COST_PER_MILE (line above) should have type annotation as long as it is public.

2020-09-19 11:05 UTC, aaltergot approved these changes

2020-09-19 17:38 UTC, JustinPihony approved these changes

2020-09-19 18:02 UTC, rajnikantsh approved these changes

2020-09-19 18:41 UTC, merged