Added kamon integration for metrics
LBNL-UCB-STI/beam pull request #3226
Opened 2021-07-05 16:16 UTC by carloscaldas

2021-07-06 15:49 UTC, JustinPihony requested changes

2021-07-06 15:49 UTC, JustinPihony commented on src/main/scala/beam/sim/BeamHelper.scala
> +    val executionSpan = Kamon.serverSpanBuilder("beamStarted", "beam").start()
This should only be set up if `isMetricsEnabled` - as above

2021-07-06 15:49 UTC, JustinPihony commented on src/main/scala/beam/sim/config/BeamExecutionConfig.scala
> +
Why is this in an object? I'd default to keeping it internal to the case class until it is needed external

2021-07-10 01:15 UTC, JustinPihony approved these changes

2021-07-20 04:01 UTC, JustinPihony commented
Can this be merged?

2022-08-30 15:10 UTC, nikolayilyin commented
Currently we already have a tool to debug akka messages, we decided to not proceed with Kamon for now

2022-08-30 15:10 UTC, closed without merging