#3341 implement enroute charging protocol
LBNL-UCB-STI/beam pull request #3373
Opened 2021-11-23 15:47 UTC by heyrutvik

- [x] Find charging stall in the middle of the path
- [x] Avoid enroute even if config values suggests, if charging level is going to be more than 80% of capacity after reaching charging stall (calculate before starting enroute trip)
- [x] Enroute trip protocol 
- [x] Tests

2021-11-23 15:53 UTC, heyrutvik commented
Test!

2021-11-23 17:59 UTC, heyrutvik commented
Test!

2021-11-24 04:35 UTC, haitamlaarabi requested changes
> Reviewed 20 of 29 files at r1, 28 of 29 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373)* status: all files reviewed, 21 unresolved discussions (waiting on @dimaopen and @heyrutvik)

___
*[src/main/resources/beam-template.conf, line 294 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEmWjr0f5ew5VcgK5W:-MpEmWjr0f5ew5VcgK5X:bsc2uyx) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/resources/beam-template.conf#L294)):*
> ```
> beam.agentsim.agents.vehicles.meanRidehailVehicleStartingSOC = "double | 1.0"
> beam.agentsim.agents.vehicles.transitVehicleTypesByRouteFile = ""
> beam.agentsim.agents.vehicles.enroute.refuelRequiredThresholdInPercent = 1.05 # 105%
> ```

I am thinking of changing this from percent to mile
___
*[src/main/resources/beam-template.conf, line 298 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEl3m9AyebQfL4Thep:-MpEl3m9AyebQfL4Theq:b-jshja9) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/resources/beam-template.conf#L298)):*
> ```
> beam.agentsim.agents.vehicles.enroute.maxDurationInSeconds = 1800 # 80% of the battery charges in 30min
> beam.agentsim.agents.vehicles.enroute.thresholdForNotWalkingToDestinationInMeters = 1000 # 1km otherwise drive. This configuration requires fast charging as well
> beam.agentsim.agents.vehicles.enroute.newLegStartDelayInSeconds = 3600 # TODO may be it should be variable, and should depend on enroute trip distance?
> ```

What's the role of this parameter?
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 887 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEo88L8payLbYcTHW-:-MpEo88L8payLbYcTHW0:bhzrqd9) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L887)):*
> ```Scala
>       val stall2DestinationCarLegs = data.enrouteState.stall2DestLegs
>       val walkTemp = data.currentTrip.head.legs.head
>       val startTime = tick + beamServices.beamConfig.beam.agentsim.agents.vehicles.enroute.newLegStartDelayInSeconds
> ```

Why would you make the agent walk after 1 hour, as the default value of newLegStartDelayInSeconds ?
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 901 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEozeh22Ym8CMCZTMW:-MpEozeiCs2iXMH1skO-:b-jv3q3h) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L901)):*
> ```Scala
>       )
>     case _ @Event(UnhandledVehicle(_, _, _), data: BasePersonData) =>
>       // TODO is this valid transition?
> ```

What would happen in this case? Would the agent continue the default workflow ? I think we should consider same steps as in "UnpluggingVehicle". We need to add driving to destination if something goes wrong.
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 968 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEqi2y5mTBgXAB2ZI3:-MpEqi2y5mTBgXAB2ZI4:b-4wjfjp) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L968)):*
> ```Scala
>         val needEnroute = {
>           asDriver && isElectric && isRefuelNeeded &&
>           data.enrouteState.notEnroute && data.enrouteState.notAttempted
> ```

what notEnroute and notAttempted means ?
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 1001 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEs7QA5-aESw_yaS5V:-MpEs7QA5-aESw_yaS5W:bzhuap1) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L1001)):*
> ```Scala
>           case ReadyToChooseParking =>
>             (false, copiedData.copy(enrouteState = EnrouteState(enroute = true)))
>           case ReleasingParkingSpot if data.enrouteState.attempted =>
> ```

Does this mean that agent attempted to enroute but failed? or attempted enroute and finished charging?
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 1014 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEsis42Wtm-E-SHROy:-MpEsis42Wtm-E-SHROz:bersadd) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L1014)):*
> ```Scala
> 
>         // complete trigger only if following conditions match
>         if ((sendCompletionNotice && data.enrouteState.notAttempted) || nextLeg.beamLeg.endTime > lastTickOfSimulation)
> ```

the only time sendCompletionNotice == true is when enrouteState is attempted. Am I missing something? So this will never be true
___
*[src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala, line 382 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEth6E26bcIUKl6k2R:-MpEth6E26bcIUKl6k2S:b4ufh3a) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala#L382)):*
> ```Scala
>                     triggerId,
>                     shiftStatus = NotApplicable,
>                     refuelTripType = if (inEnroute) Enroute else Normal
> ```

What do you need a refuelTripType?
If necessary then I would substitute Normal by Destination
___
*[src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala, line 96 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpF5csv4COsQNcBzMBO:-MpF5csv4COsQNcBzMBP:bdf03o4) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala#L96)):*
> ```Scala
>   this: PersonAgent => // Self type restricts this trait to only mix into a PersonAgent
> 
>   // TODO This might be a violation of Actor framework. Need to verify
> ```

it doesn't. we can delete this comment
___
*[src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala, line 125 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpF60nn-v1X17JRfbez:-MpF60nn-v1X17JRfbf-:b-jith5c) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala#L125)):*
> ```Scala
>       val reservedFor = VehicleManager.getReservedFor(vehicle.vehicleManagerId.get).get
>       ParkingInquiry.init(
>         calculateMidpointUtm(vehicleTrip).getOrElse(destinationUtm),
> ```

Why are you calculating the midpoint. The MNL parking/charging search already does that. I would mess results if you provide a midpoint.
___
*[src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala, line 301 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpF6oWP7D9z6d_0V5ss:-MpF6oWP7D9z6d_0V5st:b46jpq1) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala#L301)):*
> ```Scala
>           isDistanceGreaterThanThreshold && isParkingDurationSmallEnoughFor && isStallHasFastCharger
> 
>         val carIfEnroute = if (isEnroute || isDestinationChargeTurningToAnEnrouteCharge) {
> ```

this is a problem here, we cannot turn a destination charging to an enroute charging, because we are already at CAR2? Or did you find a way to make it Enroute?
___
*[src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala, line 135 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpF7Y_h4lRk0WUgyxgV:-MpF7Y_i255Ju5B9z2xD:b-vlxef8) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala#L135)):*
> ```Scala
>   }
> 
>   def unsetRe [...]

2021-11-24 09:44 UTC, heyrutvik reviewed
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373)* status: all files reviewed, 21 unresolved discussions (waiting on @dimaopen, @haitamlaarabi, and @heyrutvik)

___
*[src/main/resources/beam-template.conf, line 294 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEmWjr0f5ew5VcgK5W:-MpG98MYAvkMm_o7QWSL:bhy9ot6) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/resources/beam-template.conf#L294)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

I am thinking of changing this from percent to mile
</blockquote></details>

Will do.
___
*[src/main/resources/beam-template.conf, line 298 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEl3m9AyebQfL4Thep:-MpG8X2T4KL-w24vZl0f:bau9bch) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/resources/beam-template.conf#L298)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

What's the role of this parameter?
</blockquote></details>

The parameter is to specify how much delay we want to add to start a new leg after enroute recharging.
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 887 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEo88L8payLbYcTHW-:-MpG9GBJ-nGdQuV72lA0:bjrqyas) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L887)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

Why would you make the agent walk after 1 hour, as the default value of newLegStartDelayInSeconds ?
</blockquote></details>

Yes, so what was happening was if we schedule the next leg using available tick it was causing error in scheduler saying "tick x when 'nowInSeconds' is at y", where x << y. So I figured that agent should consider some time delay to avoid such issue. Also, the value was randomly chosen, as mentioned in template that it should be decided based on the detour distance or something. Thoughts?
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 901 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEozeh22Ym8CMCZTMW:-MpGAX3q71giW-odXhw7:bhy9ot6) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L901)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

What would happen in this case? Would the agent continue the default workflow ? I think we should consider same steps as in "UnpluggingVehicle". We need to add driving to destination if something goes wrong.
</blockquote></details>

Will do.
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 968 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEqi2y5mTBgXAB2ZI3:-MpGAkDPCLmIRDXP85iP:b-qxisae) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L968)):*
The case class defined to hold enroute related states has following two flags,
- `enroute`, it indicates that agent is on enroute charging detour
- `attempt`, it indicates that agent has attempted enroute for current trip
  - if tried but avoided due to 80% charging level condition
  - enroute charging finished, and now heading toward original destination

> what notEnroute and notAttempted means ?

These two flags are just a negation of them. We enter enrotue detour only if those conditions match.
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 1001 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEs7QA5-aESw_yaS5V:-MpGBxbR5RGn5FR0MYMh:bdqb70g) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L1001)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

Does this mean that agent attempted to enroute but failed? or attempted enroute and finished charging?
</blockquote></details>

I can see now that I can make improvement in the code here to make it less confusing. Will do. 
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 1014 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEsis42Wtm-E-SHROy:-MpGC76SAB3whPbkHKsw:b-7ayq1x) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L1014)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

the only time sendCompletionNotice == true is when enrouteState is attempted. Am I missing something? So this will never be true
</blockquote></details>

This will be removed once I simplify the code. 
___
*[src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala, line 382 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEth6E26bcIUKl6k2R:-MpGCH5HEXo-qq1NKh1j:b-9ph8yp) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala#L382)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

What do you need a refuelTripType?
If necessary then I would substitute Normal by Destination
</blockquote></details>

It'll be used to indicate what kind of refuel session it was? normal (parking at the end of the trip) or enroute. We use it in tests too.

Oh, okay. As you mentioned in other comment that we already have solution implemented for this in other branch. I'll remove this change, and merge the mentioned branch. 
___
*[src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala, line 96 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpF5csv4COsQNcBzMBO:-MpGCXUr7IVg-gLjfz3M:bebrt1w) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala#L96)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

it doesn't. we can delete this comment
</blockquote></details>

Will do
___
*[src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala, line 125 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpF60nn-v1X17JRfbez:-MpGCyaK8jDmRE_T7Jv-:bnfcc30) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala#L125)):*
> The MNL parking/charging search already does that. 
I'm not sure what it means. But if you are talking about existing code (`destinationUtm`), it uses location nearby the destination of the trip.

The purpose of calculation is fulfil one of the sub-tasks, to find charging stall in the middle of the path, rather than at the source or destination. I also posted the question about whether we have an existing such method/API, but none was exist. So I wrote one myself.

Did I misunderstand the sub-task? 
___
*[src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala, line 301 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpF6oWP7D9z6d_0V5ss:-MpGDzwZ4cQM1QyKJGPZ:b-50y1iv) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala#L301)):*
> Or did you find a way to make it Enroute?
Yes. Before coming to this state, we "travel" a leg in normal workflow. We don't do that if agent is on enroute. So we are good here.
___
*[src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala, line 135 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-Mp [...]

2021-11-25 13:11 UTC, heyrutvik commented
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 887 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEo88L8payLbYcTHW-:-MpMBFrN6u2qoRHplRK7:b58dqw6) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L887)):*
<details><summary><i>Previously, heyrutvik (Rutvik Patel) wrote…</i></summary><blockquote>

Yes, so what was happening was if we schedule the next leg using available tick it was causing error in scheduler saying "tick x when 'nowInSeconds' is at y", where x << y. So I figured that agent should consider some time delay to avoid such issue. Also, the value was randomly chosen, as mentioned in template that it should be decided based on the detour distance or something. Thoughts?
</blockquote></details>

Okay. It looks like we don't need this param. I removed it in latest commit, I'm not facing the 'tick in past compared to nowInSeconds'.  


<!-- Sent from Reviewable.io -->

2021-11-26 13:46 UTC, heyrutvik reviewed
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373)* status: 44 of 49 files reviewed, 21 unresolved discussions (waiting on @dimaopen, @haitamlaarabi, and @heyrutvik)

___
*[src/main/resources/beam-template.conf, line 294 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEmWjr0f5ew5VcgK5W:-MpQBdXBEzyGw33EhCLX:b-ih0771) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/resources/beam-template.conf#L294)):*
<details><summary><i>Previously, heyrutvik (Rutvik Patel) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

I assume you meant meters? What should be the default values for both params, noRefuelThreshold and refuelRequiredThreshol? 
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 901 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEozeh22Ym8CMCZTMW:-MpQBsuV8P8qH4WOUHSt:b-896fix) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L901)):*
<details><summary><i>Previously, heyrutvik (Rutvik Patel) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.
___
*[src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala, line 96 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpF5csv4COsQNcBzMBO:-MpQC2Di3MhPFFJh7-dO:b-896fix) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala#L96)):*
<details><summary><i>Previously, heyrutvik (Rutvik Patel) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done.
___
*[src/main/scala/beam/agentsim/events/RefuelSessionEvent.scala, line 47 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpF9Rnl4bed28pIujYd:-MpRU2oiBarE9h85YUxK:b-jbo2mu) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/events/RefuelSessionEvent.scala#L47)):*
<details><summary><i>Previously, heyrutvik (Rutvik Patel) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Currently working on merging the branch. It looks like the way we handle `vehicle2InquiryMap` storage is problematic. It only remembers the most recent parking inquiry, and what happens is, it overrides previous 'activityType'. I was testing whether refuel session correctly logs actType or not. If I'm understanding it correctly, then we can use my solution to pass activityType to refuel session  event. 


<!-- Sent from Reviewable.io -->

2021-11-30 03:09 UTC, haitamlaarabi requested changes
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373)* status: 44 of 49 files reviewed, 21 unresolved discussions (waiting on @dimaopen, @haitamlaarabi, and @heyrutvik)

___
*[src/main/resources/beam-template.conf, line 294 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEmWjr0f5ew5VcgK5W:-Mpijdz5AVVViTl2rhBi:bify8p0) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/resources/beam-template.conf#L294)):*
<details><summary><i>Previously, heyrutvik (Rutvik Patel) wrote…</i></summary><blockquote>

I assume you meant meters? What should be the default values for both params, noRefuelThreshold and refuelRequiredThreshol? 
</blockquote></details>

I will do it myself just to be sure that the calculation I made in ChargingFunctions stays correct!
___
*[src/main/resources/beam-template.conf, line 298 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEl3m9AyebQfL4Thep:-Mpijns65F7-qdYpz6vU:b-6ntav9) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/resources/beam-template.conf#L298)):*
<details><summary><i>Previously, heyrutvik (Rutvik Patel) wrote…</i></summary><blockquote>

The parameter is to specify how much delay we want to add to start a new leg after enroute recharging.
</blockquote></details>

Why would we need a delay of 1 hour after a 30min charging period ? The car can leave immediately or after a parallelism window duration after the EnrouteCharging concludes
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 887 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEo88L8payLbYcTHW-:-MpikEor-I8ITjrzsnHX:b-hhv7o3) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L887)):*
<details><summary><i>Previously, heyrutvik (Rutvik Patel) wrote…</i></summary><blockquote>

Okay. It looks like we don't need this param. I removed it in latest commit, I'm not facing the 'tick in past compared to nowInSeconds'.  
</blockquote></details>

Thanks. We should not mask errors with hacks. We would rather solve the problem than hide it.
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 901 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEozeh22Ym8CMCZTMW:-MpikTB5-SZcO4R1S1ee:bb7m07t) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L901)):*
<details><summary><i>Previously, heyrutvik (Rutvik Patel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

okay
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 968 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEqi2y5mTBgXAB2ZI3:-Mpil3Hw13b3ePALyRIS:b-1zw3e1) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L968)):*
<details><summary><i>Previously, heyrutvik (Rutvik Patel) wrote…</i></summary><blockquote>

The case class defined to hold enroute related states has following two flags,
- `enroute`, it indicates that agent is on enroute charging detour
- `attempt`, it indicates that agent has attempted enroute for current trip
  - if tried but avoided due to 80% charging level condition
  - enroute charging finished, and now heading toward original destination

> what notEnroute and notAttempted means ?

These two flags are just a negation of them. We enter enrotue detour only if those conditions match.
</blockquote></details>

Why does it attempt charging if charging level condition is 80%. I think
We should allow multiple enroute happening one after another if the battery is not enough to reach destination. Which means EnrouteCharge then when leaving recalculate remained energy, if not enough to destination we should ask for enroute between current stall and original destination. 
In other words, I do not see reason for the flag "attempt", but "enroute" flag makes sense. 
___
*[src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala, line 382 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEth6E26bcIUKl6k2R:-Mpimcei4D_3Jd31JAfY:b-9js7jr) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala#L382)):*
<details><summary><i>Previously, heyrutvik (Rutvik Patel) wrote…</i></summary><blockquote>

It'll be used to indicate what kind of refuel session it was? normal (parking at the end of the trip) or enroute. We use it in tests too.

Oh, okay. As you mentioned in other comment that we already have solution implemented for this in other branch. I'll remove this change, and merge the mentioned branch. 
</blockquote></details>

I think Justin approved the PR. I will look into it and merge
___
*[src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala, line 125 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpF60nn-v1X17JRfbez:-MpimsYw79enRxHj5lh2:b-49uwnm) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala#L125)):*
<details><summary><i>Previously, heyrutvik (Rutvik Patel) wrote…</i></summary><blockquote>

> The MNL parking/charging search already does that. 
I'm not sure what it means. But if you are talking about existing code (`destinationUtm`), it uses location nearby the destination of the trip.

The purpose of calculation is fulfil one of the sub-tasks, to find charging stall in the middle of the path, rather than at the source or destination. I also posted the question about whether we have an existing such method/API, but none was exist. So I wrote one myself.

Did I misunderstand the sub-task? 
</blockquote></details>

I actually did that subtask before I shared with you the branch. In ChargingFunction and Parking function, we are using a Ellipse to look for a station between origin and destination. The whole work I done in EnrouteCharging was mainly to calculate the midpoint. We will need to chat on zoom about it.
___
*[src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala, line 301 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpF6oWP7D9z6d_0V5ss:-MpinOcU58N-Ga2kJ09C:bem1ozd) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala#L301)):*
<details><summary><i>Previously, heyrutvik (Rutvik Patel) wrote…</i></summary><blockquote>

> Or did you find a way to make it Enroute?
Yes. Before coming to this state, we "travel" a leg in normal workflow. We don't do that if agent is on enroute. So we are good here.
</blockquote></details>

I still don't understand. Let's talk about it on Zoom
___
*[src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala, line 135 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpF7Y_h4lRk0WUgyxgV:-MpinX-_DuvaZbqBH4CQ:bhc7q6y) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala#L135)):*
<details><summary><i>Previously, heyrutvik (Rutvik Patel) wrote…</i></summary><blockquote>

So in the scenario when agent figures out that enroute can be avoided (charging level > 80%), we use this method to unset the parking stall which we stored while receiving charging stall inquiry response.  
</blockquote></details>

I feel that something is wrong here, but I might be mistaken. Let's talk about on Zoom
___
*[src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala, line 664 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpF7tDm4emGuheGMHoj:-MpinhbK-3H5Sla59wj2:b-mc6kq7) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bf [...]

2021-12-01 10:53 UTC, heyrutvik reviewed
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373)* status: 44 of 49 files reviewed, 21 unresolved discussions (waiting on @dimaopen, @haitamlaarabi, and @heyrutvik)

___
*[src/main/resources/beam-template.conf, line 294 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEmWjr0f5ew5VcgK5W:-MppaFb-DFMsIECanrND:b-bty3uv) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/resources/beam-template.conf#L294)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

I will do it myself just to be sure that the calculation I made in ChargingFunctions stays correct!
</blockquote></details>

Sure. Thanks.
___
*[src/main/resources/beam-template.conf, line 298 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEl3m9AyebQfL4Thep:-MppaHevEx-pJMyfSZ3h:b-896fix) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/resources/beam-template.conf#L298)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

Why would we need a delay of 1 hour after a 30min charging period ? The car can leave immediately or after a parallelism window duration after the EnrouteCharging concludes
</blockquote></details>

Done.
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 887 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEo88L8payLbYcTHW-:-MppaMEB0_tHNpEn2t-u:b-lni3zf) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L887)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

Thanks. We should not mask errors with hacks. We would rather solve the problem than hide it.
</blockquote></details>

I agree. How tick works was a bit black box for me. I've made an appropriate change, but it seems like once in a while agent dies due to the same error. Let's talk about it over ZOOM call.
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 968 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpEqi2y5mTBgXAB2ZI3:-MppamIOBu0P3Hl-iNJU:b-e8kumc) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L968)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

Why does it attempt charging if charging level condition is 80%. I think
We should allow multiple enroute happening one after another if the battery is not enough to reach destination. Which means EnrouteCharge then when leaving recalculate remained energy, if not enough to destination we should ask for enroute between current stall and original destination. 
In other words, I do not see reason for the flag "attempt", but "enroute" flag makes sense. 
</blockquote></details>

Got it. We had such a behaviour in my initial draft where a vehicle keep looking for charging stall if its required. I thought it's flawed design. I also use 'attempt' to avoid re-searching charging stall if 80% charge is available. Let's talk about it over ZOOM call.
___
*[src/main/scala/beam/agentsim/infrastructure/ChargingNetworkManager.scala, line 100 at r3](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpFA_HE5sTWoKAL4rU9:-MppbkLX99nLrYoVZ40j:b-ye2v1) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/eaaecb274bf6c470bfabd32ef5aca1bc697bcddd/src/main/scala/beam/agentsim/infrastructure/ChargingNetworkManager.scala#L100)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

If it doesn't return a stall then we have to continue with normal workflow.
</blockquote></details>

Handled. Done.


<!-- Sent from Reviewable.io -->

2021-12-29 21:01 UTC, JustinPihony requested changes
Most are FYI - there is one deviation to be addressed at least.

2021-12-29 21:01 UTC, JustinPihony commented on src/main/scala/beam/router/skim/readonly/DriveTimeSkims.scala
> +class DriveTimeSkims() extends AbstractSkimmerReadOnly {}
Why remove the `case`s?

2021-12-29 21:01 UTC, JustinPihony commented on src/main/scala/beam/agentsim/agents/PersonAgent.scala
> +      log.debug(
Should this be a warning - or even an error?

2021-12-29 21:01 UTC, JustinPihony commented on src/main/scala/beam/agentsim/agents/PersonAgent.scala
> +        val isSharedVehicle = beamVehicles(nextLeg.beamVehicleId)
Can you use `vehicle` that was already created earlier?

2021-12-29 21:01 UTC, JustinPihony commented on src/main/scala/beam/agentsim/agents/PersonAgent.scala
> +        val copiedData = data.copy(
Is this even used? As far as I see it is only used for further copying, but never used.

2021-12-29 21:01 UTC, JustinPihony commented on src/main/scala/beam/agentsim/infrastructure/ChargingFunctions.scala
> +  def ifEnrouteChargingTheFastChargingOnly(zone: ParkingZone[GEO], inquiry: ParkingInquiry): Boolean = {
Typo - ...ThenFast...

2021-12-29 21:01 UTC, JustinPihony commented on src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala
> +              Vector(ScheduleTrigger(StartLegTrigger(tick, nextLeg), self))
Should this be `nextLeg.startTime` from the original code. I believe only the enroute is new - otherwise it should be the original logic

2021-12-29 21:01 UTC, JustinPihony commented on src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala
> +          // get car route from stall to destination, TODO note we give a dummy start time and update later based on drive time to stall
Should the start time be something absurd to track it back in case something goes off track?

2022-01-02 08:54 UTC, haitamlaarabi requested changes
> Reviewed 8 of 18 files at r6, 1 of 24 files at r7, 18 of 23 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373)* status: all files reviewed, 29 unresolved discussions (waiting on @dimaopen, @haitamlaarabi, @heyrutvik, and @JustinPihony)

___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 881 at r9](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpCTktSch4E3hGJB-WT-r9-881:-MsOvGG36NlHHLfKw0u_:bq808tk) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/9b0e60e319ed67b402f4a7e17e41e502213fef11/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L881)):*
<details><summary><i>Previously, JustinPihony (Justin Pihony) wrote…</i></summary><blockquote>

Should this be a warning - or even an error?
</blockquote></details>

I agree. Let's change it from debug to warn
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 977 at r9](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MsOvox7DZj4s5-Mpzbw:-MsOvox7DZj4s5-Mpzbx:b-99hkba) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/9b0e60e319ed67b402f4a7e17e41e502213fef11/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L977)):*
> ```Scala
>         val vehicleTrip = data.restOfCurrentTrip.takeWhile(_.beamVehicleId == firstLeg.beamVehicleId)
>         val totalDistance = vehicleTrip.map(_.beamLeg.travelPath.distanceInM).sum
>         val refuelRequiredThresholdInMeters = totalDistance * enrouteConfig.refuelRequiredThresholdInPercent
> ```

I am not seeing the change I introduced to how we compute this value.
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 984 at r9](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpCTktSch4E3hGJB-WT-r9-984:-MsOw43u4hwV0hVccWrW:b7anmnw) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/9b0e60e319ed67b402f4a7e17e41e502213fef11/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L984)):*
<details><summary><i>Previously, JustinPihony (Justin Pihony) wrote…</i></summary><blockquote>

Can you use `vehicle` that was already created earlier?
</blockquote></details>

good call
___
*[src/main/scala/beam/agentsim/agents/PersonAgent.scala, line 996 at r9](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpCTktSch4E3hGJB-WT-r9-996:-MsOwKj51T9IRHQPCU-Y:b2k5nfg) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/9b0e60e319ed67b402f4a7e17e41e502213fef11/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L996)):*
<details><summary><i>Previously, JustinPihony (Justin Pihony) wrote…</i></summary><blockquote>

Is this even used? As far as I see it is only used for further copying, but never used.
</blockquote></details>

this section of the code is a bit confusing I have tried to change it once, but since there was a bug to solve first I retracted my changes
___
*[src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala, line 226 at r9](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpCTktSch4E3hGJB-WW-r9-226:-MsOxOrN4odGr9cVJjUY:bbspxdr) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/9b0e60e319ed67b402f4a7e17e41e502213fef11/src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala#L226)):*
<details><summary><i>Previously, JustinPihony (Justin Pihony) wrote…</i></summary><blockquote>

Should this be `nextLeg.startTime` from the original code. I believe only the enroute is new - otherwise it should be the original logic
</blockquote></details>

I agree. @heyrutvik was nextLeg.startTime causing the old tick ? if yes  maybe we should take max of (next.Leg.startTime) and (tick). Otherwise, let's keep normal workflow with nextLeg.startTime
___
*[src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala, line 275 at r9](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3373#-MpCTktSch4E3hGJB-WW-r9-275:-MsOy-Y4B_VWI1Qy_8X7:b-iztc19) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/9b0e60e319ed67b402f4a7e17e41e502213fef11/src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala#L275)):*
<details><summary><i>Previously, JustinPihony (Justin Pihony) wrote…</i></summary><blockquote>

Should the start time be something absurd to track it back in case something goes off track?
</blockquote></details>

I might have introduced that comment at some point an forgot why I wrote that. The code changed a lot since then


<!-- Sent from Reviewable.io -->

2022-01-03 07:15 UTC, heyrutvik commented
We were facing some issues in the enroute protocol such as, stuckness and agent dieing due to 'tick in the past'. @dimaopen worked on top of this branch to resolve those issues. Dima's branch is `do/#3341-enroute-charing-fix-1`. I'm closing this PR as it's out dated. cc @JustinPihony @haitamlaarabi

2022-01-03 07:15 UTC, closed without merging