External script at AWS EC2 instances that saves beam thread dump
LBNL-UCB-STI/beam pull request #3559
Opened 2022-07-13 11:49 UTC by dimaopen

1. Moved scheduler state files to the root of the output folder.
2. Save thread dump by scheduler.
3. Save thread dump and kill beam by an external process.

2022-07-13 12:41 UTC, nikolayilyin requested changes
I think the content of /tmp/slack_notification does not match it's name, either the file name should be changed, or the new script should be moved.

2022-07-13 12:41 UTC, nikolayilyin commented on aws/src/main/python/beam_lambda/lambda_function.py
>        path: /tmp/slack_notification
I do not understand what this part do. 
Our slack notifications do not contain text from first row of file - I am not sure it is working at all, or, if it is - where to look for these notifications.
The added row should sent slack notifications too?
It seems the content of 'beam stuck guard' should kill beam if it is stuck, if so, this is not a place for such script.

2022-07-14 04:03 UTC, JustinPihony commented on aws/src/main/python/beam_lambda/lambda_function.py
> +          */10 * * * * /home/ubuntu/beam_stuck_guard.sh
This should be stored somewhere else for backup, but overall it should be built into the image - not constantly added via a lambda. We could add a check for the appropriate files and setup in the image updating lambda (but that is likely not necessary)

2022-07-14 04:03 UTC, JustinPihony commented on aws/src/main/python/beam_lambda/lambda_function.py
> +          */10 * * * * /home/ubuntu/beam_stuck_guard.sh
The biggest question mark would be if 10 minutes is long enough to get to the point of starting up beam from instance start - granted I don't think that changes with this impl or my suggested one

2022-07-14 14:41 UTC, nikolayilyin commented on aws/src/main/python/beam_lambda/lambda_function.py
>        path: /tmp/slack_notification
I suggest to remove old and not working part from slack-notification script and rename the script into something appropriate to its functionality - 'cron-tasks' or something like that

2022-07-15 13:06 UTC, dimaopen commented on aws/src/main/python/beam_lambda/lambda_function.py
> +          */10 * * * * /home/ubuntu/beam_stuck_guard.sh
> This should be stored somewhere else for backup, but overall it should be built into the image

I generally agree that it's better to keep the script in the image. How can I do it? By the way if we need to fix/modify the script in the future would it be an easy task (comparing to changing the lambda)?
The script itself is at https://github.com/LBNL-UCB-STI/beam/blob/4cf7a9811d2dbf84b80a0b19ca3ccd1d723872b2/aws/src/main/python/beam_lambda/lambda_function.py#L138-L155

2022-07-15 13:08 UTC, dimaopen commented on aws/src/main/python/beam_lambda/lambda_function.py
> +          */10 * * * * /home/ubuntu/beam_stuck_guard.sh
> The biggest question mark would be if 10 minutes is long enough to get to the point of starting up beam from instance start

If beam is not run that script just exists.
`pgrep -f RunBeam || exit 0 `

2022-07-15 13:45 UTC, nikolayilyin reviewed
lgtm

2022-07-15 13:45 UTC, nikolayilyin commented
test!

2022-07-18 15:25 UTC, nikolayilyin approved these changes

2022-07-18 15:25 UTC, merged

2022-07-18 18:10 UTC, JustinPihony commented on aws/src/main/python/beam_lambda/lambda_function.py
> +          */10 * * * * /home/ubuntu/beam_stuck_guard.sh
For future reference, the way to build it into the image is to take the AMI and start up an instance (usually you only need a small instance for rebasing). Then make the changes needed inside of that instance. Once done go back to the AWS console, choose the instance, and hit "Image and Templates > Create Image". Next you go to the AMIs and find the new AMI and hit Copy Image, changing the region to us-west-1 and us-east-1 to create the base image for those regions also. Finally you'll need to change the lambda environment variables to point to the new image ids for simulateBeam. Oh, and you also need to update jenkins at https://beam-ci.tk/configureClouds/ - changing the AMI IDs which reference the old one to the new one. It is more onerous than the current way, but good if steady. If expected to change, then yes, leaving in the lambda is better. I would assume this to be steady. Ultimately, it probably doesn't add much overhead, other than clutter to the lambda code, so fine to leave.