Read in experienced plans from previous beam runs and SelectExpBeta from them
LBNL-UCB-STI/beam pull request #3814
Opened 2023-12-18 23:33 UTC by zneedell

Only used in PILATES for now -- allows for BEAM to read in agents' plan memories during a PILATES warmstart and select from possible daily plans based on their utility. Has some additional commits that are also in other PRs needed to get it to compile.

2023-12-19 00:19 UTC, zneedell commented
Test!

2023-12-19 19:04 UTC, zneedell commented
Test!

2023-12-22 15:32 UTC, dimaopen requested changes
Most of these are up to the developer. But the big pieces of the same code should be reused.

2023-12-22 15:32 UTC, dimaopen commented on src/main/scala/beam/utils/scenario/PreviousRunPlanMerger.scala
> +  private def findLatestOutputDirectory(outputPath: Path, dirPrefix: String) = {
We can reuse code from lines 196-199

2023-12-22 15:32 UTC, dimaopen commented on src/main/scala/beam/utils/scenario/PreviousRunPlanMerger.scala
>        (itDir, itNumber) <- findAllLastIterationDirectories(outputPath, dirPrefix)
The following 7 lines is the same as 157-164. Could we extract a method with a self-explanatory name?

2023-12-22 15:32 UTC, dimaopen commented on src/main/scala/beam/utils/scenario/UrbanSimScenarioLoader.scala
Maybe remove this val completely? or we need a comment why we keep it.

2023-12-22 15:32 UTC, dimaopen commented on src/main/scala/beam/utils/scenario/UrbanSimScenarioLoader.scala
> +    leg.getAttributes.putAttribute("trip_id", planElement.tripId)
This is the only line it differs from `BeamScenarioLoader.buildAndAddLegToPlan`. I think we can reuse the same code.

2023-12-22 15:32 UTC, dimaopen commented on src/main/resources/beam-template.conf
> +beam.replanning.replanningPenaltyInDollars = "double | 100.0"
If we want to make beam more or less an internation product we can use something like `replanningMonetaryPenalty`. Though in this case we should change other references to dollar.

2024-03-18 22:28 UTC, zneedell commented
Merged in with #3829

2024-03-18 22:28 UTC, closed without merging