Freight enhancement and validation script
LBNL-UCB-STI/beam pull request #3825
Opened 2024-03-05 04:01 UTC by haitamlaarabi

2024-03-05 04:03 UTC, haitamlaarabi commented
Test!

2024-03-05 06:03 UTC, haitamlaarabi commented
Test now!

2024-03-05 23:56 UTC, haitamlaarabi commented
Test now!

2024-03-06 01:30 UTC, haitamlaarabi commented
test!

2024-03-06 04:24 UTC, haitamlaarabi commented
test!

2024-03-06 13:25 UTC, dimaopen requested changes
Looks good except a few requests

2024-03-06 13:25 UTC, dimaopen commented on src/main/resources/beam-template.conf
> +beam.physsim.minCarSpeedInMetersPerSecond = "double | 0.5"
We need to find and replace all the entries of this changed param in the whole project (including rst files)

2024-03-06 13:25 UTC, dimaopen commented on src/main/java/beam/physsim/jdeqsim/cacc/sim/JDEQSimulation.java
> +                        minimumRoadSpeedInMetersPerSecond,
If we don't use `adjustedMinimumRoadSpeedInMetersPerSecond` anymore then we need to remove it from the project completely (including documentation)

2024-03-06 13:25 UTC, dimaopen commented on src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
> +        log.info(s"RouteE: Vehicle ${currentBeamVehicle.id} - fuelConsumed: ${fuelConsumed}")
Shouldn't these 3 log entries go to debug instead of info?

2024-03-06 22:59 UTC, haitamlaarabi commented on src/main/java/beam/physsim/jdeqsim/cacc/sim/JDEQSimulation.java
> +                        minimumRoadSpeedInMetersPerSecond,
deleted all occurrence and I mentioned this in the template file:
```
beam.physsim.minCarSpeedInMetersPerSecond = "double | 0.5" # heads up, this affects beam.physsim.jdeqsim.cacc
# The following parameter has been replaced by beam.physsim.minCarSpeedInMetersPerSecond = 2.0 
# beam.physsim.jdeqsim.cacc.adjustedMinimumRoadSpeedInMetersPerSecond = "double | 1.3"
```

2024-03-06 22:59 UTC, haitamlaarabi commented on src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
> +        log.info(s"RouteE: Vehicle ${currentBeamVehicle.id} - fuelConsumed: ${fuelConsumed}")
it was a temporary debug log. I'm removing it.

2024-03-06 23:01 UTC, haitamlaarabi commented
Test!

2024-03-07 07:26 UTC, dimaopen approved these changes
Looks good. Though these params:
`adjustedMinimumRoadSpeedInMetersPerSecond`
`quick_fix_minCarSpeedInMetersPerSecond`
are still in the production config files. May be we cannot remove them because of the old beam code that can be used with production.
Also DrivesVehicle still contains some log.info that can pollute the log file.

2024-03-07 07:26 UTC, dimaopen commented on src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
> +        log.info(s"RouteE: Vehicle ${currentBeamVehicle.id} - vehicleType ${currentBeamVehicle.beamVehicleType.id}")
This entry should probably be removed too

2024-03-07 07:26 UTC, dimaopen commented on src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
> +        log.info(s"RouteE: Vehicle ${currentBeamVehicle.id} - payloadInKg: ${payloadInKg}")
This entry should probably be removed too

2024-03-07 23:12 UTC, haitamlaarabi commented
> adjustedMinimumRoadSpeedInMetersPerSecond

I think default value of quick_fix_minCarSpeedInMetersPerSecond is fine, since it wasn't solving the problem it was supposed to solve anyway.

2024-03-07 23:15 UTC, haitamlaarabi commented
test!

2024-03-08 00:19 UTC, merged