Merging zn/PILATES
LBNL-UCB-STI/beam pull request #3829
Opened 2024-03-06 05:30 UTC by haitamlaarabi

@zneedell made several changes to zn/PILATES branch that are not in develop. I merged the branch with hl/freight-develop-calibration and develop, to have a branch that contains all required changes to run BEAM-Freight calibration. Please review carefully this branch and make sure it won't break develop.

2024-03-06 05:30 UTC, haitamlaarabi commented
test!

2024-03-06 23:03 UTC, haitamlaarabi commented
test!

2024-03-06 23:05 UTC, haitamlaarabi commented
test!

2024-03-06 23:55 UTC, haitamlaarabi commented
test!

2024-03-07 21:00 UTC, haitamlaarabi commented
test!

2024-03-08 08:17 UTC, nikolayilyin commented
test!

2024-03-08 19:26 UTC, zneedell commented
Test!

2024-03-08 23:56 UTC, zneedell commented
Test now!

2024-03-09 00:29 UTC, zneedell commented
Test!

2024-03-09 01:08 UTC, haitamlaarabi commented
test!

2024-03-09 02:01 UTC, haitamlaarabi commented
test!

2024-03-09 10:34 UTC, nikolayilyin commented
test!

2024-03-11 23:23 UTC, haitamlaarabi commented
test!

2024-03-12 09:00 UTC, nikolayilyin requested changes

2024-03-12 09:00 UTC, nikolayilyin commented on src/main/scala/beam/router/skim/ActivitySimPathType.scala
> +      BIKE
This condition is confusing.
It would be great to have some clarification here, for example - what modes are we expecting here to be, why exactly 3 and not 2 (i.e. WALK and BIKE).
Even better - to check for specific modes and not their count.

2024-03-12 09:00 UTC, nikolayilyin commented on src/main/scala/beam/utils/scenario/UrbanSimScenarioLoader.scala
> +  private val wereCoordinatesInWGS = false //beamScenario.beamConfig.beam.exchange.scenario.convertWgs2Utm // make false
Should it be always false? In that case it would be better to completely remove this flag.

2024-03-14 18:09 UTC, zneedell commented on src/main/scala/beam/router/skim/ActivitySimPathType.scala
> +      BIKE
Yep this was a bug, thanks for catching it!

2024-03-14 18:09 UTC, zneedell commented on src/main/scala/beam/utils/scenario/UrbanSimScenarioLoader.scala
> +  private val wereCoordinatesInWGS = false //beamScenario.beamConfig.beam.exchange.scenario.convertWgs2Utm // make false
Fixed, thanks!

2024-03-14 18:11 UTC, zneedell commented
Test!

2024-03-15 10:15 UTC, nikolayilyin approved these changes
lgtm

2024-03-15 10:15 UTC, merged